---
- name: K8s | Deployment for Dojo

  hosts: k8s_master

  environment: "{{ proxy_env | default({}) }}"

  serial: 1

  become: yes

  roles:
    - nephelaiio.plugins

  tasks:

    - name: include private variables
      include_vars:
        dir: "{{ item }}"
      with_items: "{{ vaults }}"
    
    - name: set facts for service files with runtime settings
      set_fact:
        working_dir_host: "/wpn-resources/deploys"
        working_dir_container: "{{ dotnet_default_working_dir | default('/app') }}"

    - name: create service directory
      file:
        path: "{{ working_dir_host }}"
        state: directory
      register: service_directory

    - name: copy dojo_deploy.yml template
      template:
        src: /deploys/dojo_deploy.yml
        dest: "{{ working_dir_host }}/dojo_deploy.yml"
      register: copy_dojo_deploy
      when:
        - service_directory is succeeded
